// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0
// source: empty/empty.proto

package empty

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmptyServiceClient is the client API for EmptyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmptyServiceClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type emptyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmptyServiceClient(cc grpc.ClientConnInterface) EmptyServiceClient {
	return &emptyServiceClient{cc}
}

func (c *emptyServiceClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/empty.empty.EmptyService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmptyServiceServer is the server API for EmptyService service.
// All implementations must embed UnimplementedEmptyServiceServer
// for forward compatibility
type EmptyServiceServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedEmptyServiceServer()
}

// UnimplementedEmptyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmptyServiceServer struct {
}

func (UnimplementedEmptyServiceServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEmptyServiceServer) mustEmbedUnimplementedEmptyServiceServer() {}

// UnsafeEmptyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmptyServiceServer will
// result in compilation errors.
type UnsafeEmptyServiceServer interface {
	mustEmbedUnimplementedEmptyServiceServer()
}

func RegisterEmptyServiceServer(s grpc.ServiceRegistrar, srv EmptyServiceServer) {
	s.RegisterService(&EmptyService_ServiceDesc, srv)
}

func _EmptyService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmptyServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/empty.empty.EmptyService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmptyServiceServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// EmptyService_ServiceDesc is the grpc.ServiceDesc for EmptyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmptyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "empty.empty.EmptyService",
	HandlerType: (*EmptyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _EmptyService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "empty/empty.proto",
}
